services:
  - type: web
    name: property-works
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm install --prefix backend
    startCommand: node backend/server.js
    envVars:
      - key: NODE_OPTIONS
        value: --max-old-space-size=450
