/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RefundCancellationPolicyRouteImport } from './routes/refund-cancellation-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as KnowledgeCenterIndexRouteImport } from './routes/knowledge-center.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as KnowledgeCenterArticleSlugRouteImport } from './routes/knowledge-center.$articleSlug'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundCancellationPolicyRoute =
  RefundCancellationPolicyRouteImport.update({
    id: '/refund-cancellation-policy',
    path: '/refund-cancellation-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeCenterIndexRoute = KnowledgeCenterIndexRouteImport.update({
  id: '/knowledge-center/',
  path: '/knowledge-center/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeCenterArticleSlugRoute =
  KnowledgeCenterArticleSlugRouteImport.update({
    id: '/knowledge-center/$articleSlug',
    path: '/knowledge-center/$articleSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-cancellation-policy': typeof RefundCancellationPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/knowledge-center/$articleSlug': typeof KnowledgeCenterArticleSlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/knowledge-center/': typeof KnowledgeCenterIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-cancellation-policy': typeof RefundCancellationPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/knowledge-center/$articleSlug': typeof KnowledgeCenterArticleSlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/knowledge-center': typeof KnowledgeCenterIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-cancellation-policy': typeof RefundCancellationPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/knowledge-center/$articleSlug': typeof KnowledgeCenterArticleSlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/knowledge-center/': typeof KnowledgeCenterIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faq'
    | '/privacy-policy'
    | '/refund-cancellation-policy'
    | '/services'
    | '/terms-and-conditions'
    | '/knowledge-center/$articleSlug'
    | '/projects/$projectId'
    | '/knowledge-center/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faq'
    | '/privacy-policy'
    | '/refund-cancellation-policy'
    | '/services'
    | '/terms-and-conditions'
    | '/knowledge-center/$articleSlug'
    | '/projects/$projectId'
    | '/knowledge-center'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faq'
    | '/privacy-policy'
    | '/refund-cancellation-policy'
    | '/services'
    | '/terms-and-conditions'
    | '/knowledge-center/$articleSlug'
    | '/projects/$projectId'
    | '/knowledge-center/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundCancellationPolicyRoute: typeof RefundCancellationPolicyRoute
  ServicesRoute: typeof ServicesRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  KnowledgeCenterArticleSlugRoute: typeof KnowledgeCenterArticleSlugRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  KnowledgeCenterIndexRoute: typeof KnowledgeCenterIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-cancellation-policy': {
      id: '/refund-cancellation-policy'
      path: '/refund-cancellation-policy'
      fullPath: '/refund-cancellation-policy'
      preLoaderRoute: typeof RefundCancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-center/': {
      id: '/knowledge-center/'
      path: '/knowledge-center'
      fullPath: '/knowledge-center/'
      preLoaderRoute: typeof KnowledgeCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-center/$articleSlug': {
      id: '/knowledge-center/$articleSlug'
      path: '/knowledge-center/$articleSlug'
      fullPath: '/knowledge-center/$articleSlug'
      preLoaderRoute: typeof KnowledgeCenterArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundCancellationPolicyRoute: RefundCancellationPolicyRoute,
  ServicesRoute: ServicesRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  KnowledgeCenterArticleSlugRoute: KnowledgeCenterArticleSlugRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  KnowledgeCenterIndexRoute: KnowledgeCenterIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
